### ISSUE TITLE
Installation instructions are not clear

### ISSUE THREAD

**Issue by mariosmikroulis** [ESX-PUBLIC/esx_joblogs#12]
I've tried to follow the instructions of the repo about how to install the mod and it is not clear.

For instance, I've cloned the repo and added it inside the server-data/resource folder,  I've added the "start esx_joblogs" inside the server.cfg and I got stuck to the third and fourth step. I will be providing as a job example the police to demonstrate my confusion and demonstrate to you what is not clear.

What do you mean by saying "Go to compatible ressource and turn Config.EnableJobLogs to true"? Do you mean that I have to go to esx_police/config.lua and add the "Config.EnableJobLogs"? I've tried that but it didn't log anything.

What do you mean by saying "Use compatible version of job include in ressource folder "CompatibleRessource" "? Do I have to copy or crop the esx_police inside the CompatibleResouce, which is located inside the esx_joblogs? If I crop it, the server won't recognise the police as a resource. If I copy it, the esx_joblogs doesn't seem to create the logs.

I can also provide a discord channel and TeamViewer credentials for the support of this issue my team is faced with. The first two steps are easy for sure, since they are the initial steps you always do for required mods, but the next two are not explained properly and do not give clarity to new fivem developers.

I believe I've given enough details for you to understand what I found difficult.

**Comment by rex2630** [comment]
https://github.com/ESX-PUBLIC/esx_joblogs/blob/master/CompatibleRessource/esx_billing/config.lua#L3

**Comment by rex2630** [comment]
Whats difficult on that, man?

**Comment by ghost** [comment]
how can we start the job from this file?????

**Comment by mariosmikroulis** [comment]
We've done it already dude. I've already added the line of code you mentioned. It doesn't seem to work! Can you give us a hand or not?

**Comment by mariosmikroulis** [comment]
Also what about the other parts? Do I have to crop all the jobs like police inside the ./server-data/resources/esx_joblogs/CompatibleRessource and delete it from
./server-data/resources/esx_police? I've tried to do that but it wasn't loading the esx_police anymore for some strange reason, inc the rest of the jobs.
Do I just copy it? can u talk me though the steps in details?
